version: "3"
services:
    node-solid-pollution:
        # restart: always
        # build: .
        image: express_node-solid-pollution:v2
        container_name: node-solid-polltion-container
        # image: node:v1
        # image: express_node-solid-pollution:v1
        # links:
        #     - mongo-solid-pollution
        networks:
            - solid-pollution-network
        depends_on:
            - mongo-solid-pollution
        # ports:
        #     - 9010:3000
        volumes:
            - ./:/code
        stdin_open: true # -i interactive
        tty: true # -t tty
        privileged: true
        entrypoint: ["/bin/sh"] # 执行 sh
    mongo-solid-pollution:
        image: express-mongo-solid-pollution:v2
        container_name: mongo-solid-polltion-container
        # image: mongo:4.2
        # platform: arm64
        # image: express_mongo-solid-pollution:v1
        # expose:
        #     - 27017
        networks:
            - solid-pollution-network
        # ports:
        #     - 27017:27017
        # volumes:
        #     - ~/data/db:/data/db
        #     - mongodb:/data/db
        # entrypoint: ["/bin/sh"]
        # stdin_open: true # -i interactive
        # tty: true # -t tty
        # privileged: true
        # entrypoint: ["/bin/sh"] # 执行 sh
        entrypoint: ["mongod", "--bind_ip_all"] # 执行 sh
        # entrypoint: ["docker-entrypoint.sh"] # 执行 sh
# volumes:
#     mongodb:
networks:
    solid-pollution-network:
        driver: bridge
